### ISSUE TITLE
Компонента движения CharacterMovementComponent

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#11]
**Общее описание**
Оформить прототип движения в компоненту движения.

**ТЗ**
В новой ветке `feature/movement` реализовать компоненту движения персонажа (наследует Node):
![image](https://github.com/Dkoplik/Paint-it-Black/assets/101090199/54eaad71-2c35-4635-8348-2d34dbbb357e)
MovementResource уже есть в ветке `develop`, поэтому его реализовывать не надо. Сигналы нужны для того, чтобы узнать текущее состояние персонажа и включить соответствующую анимацию.
- Поле `movement_resource` можно сделать с атрибутом `@export`
- Поле `character_body` **нужно** сделать с атрибутом `@export`, поскольку там будет храниться ссылка на узел, который надо двигать
- Метод `move` двигает персонажа влево или вправо, в зависимости от входящего вектора (интересует только `x` составляющая)
- Метод `jump` заставляет персонажа прыгнуть, все параметры прыжка заданы в ресурсе.

Остальная логика зависит от окружения или состояния персонажа, по типу скольжения по стене (упереться в стену и нет пола под ногами), поэтому нет никакого смысла для такого функционала делать публичные функции. Однако, если удобно, то внутреннюю логику можно разделить на приватные функции (названия начинаются с `_`).

На всякий случай, видео про [Resource в Godot](https://youtu.be/vzRZjM9MTGw).

**Comment by Dkoplik** [comment]
Ветку `prototype/movement` можно взять за основу в реализации, но её лучше никуда не сливать. Также в самой компоненте движения нет какой-либо обработки управления, она только даёт функционал по движению. В целях тестирования можно будет создать тестовый скрипт в узле `CharacterBody2D`, который будет вызывать методы `move` и `jump` в зависимости от управления. Сама компонента должна быть дочерним узлом узла `CharacterBody2D`, а ссылка на родительский `CharacterBody2D` задаётся через окно inspector (поле `character_body`).

**Comment by xzxolop** [comment]
Сделал компоненту движения
