### ISSUE TITLE
Нарисовать spritesheet игрока

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#12]
**Общее описание**
Нарисовать spritesheet игрока со всеми его конечностями по отдельности. Суть заключается в том, что игрока надо будет разделить на отдельные спрайты по конечностям, дабы в анимации задать движение уже самих спрайтов. Такую анимацию сделать намного проще, чем полноценную раскадровку, да и деление по конечностям необходимо для некоторых процедурных анимаций.

**ТЗ**
Нарисовать png картинку, где игрок будет разобран по частям (условные кости). В итоге должны получиться следующие спрайты:
- Голова
- Туловище (пока не уверен, но, возможно, потом его надо будет поделить на 2 части)
- Клинок
- Руки:
  - Плечо
  - Предплечье
  - Кисть
- Ноги:
  - Верхняя часть (выше колена)
  - Нижняя часть (ниже колена)
  - Стопы

**Comment by Gamzatov1** [comment]
нарисовал в комите 222f9022d01a5f08f069f1a3a3c8f7601562c525
