### ISSUE TITLE
Компонента BasicHitBox

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#20]
**Общее описание**
Написать реализацию для компоненты BasicHitBox.

**ТЗ**
Задание выполнять в ветке `feature/BasicHitBox` (немного некорректный формат имени задал, но уже не хочу удалять ветку), после чего сделать Pull-request из неё в `develop`.

Интерфейс уже готов в файле [basic_hit_box.gd](https://github.com/Dkoplik/Paint-it-Black/blob/develop/Paint-it-Black/basic_hit_box.gd), надо написать реализацию по комментариям. Задание довольно простое:
1. Свзять сигнал из Area2D с локальным методом, чтобы сделать автоматическую передачу урона
2. Написать сам метод, который передаёт параметры атаки для обработки в hurtbox

![image](https://github.com/Dkoplik/Paint-it-Black/assets/101090199/29e508f0-e13d-4240-ab58-dd981eea9af6)

**Тестирование**
Создал сцену `test` с hitbox и hurtbox, причём hitbox следует за мышкой. Более того, уже есть скрипт, который пишет в консоль получаемый урон. В общем, если нигде не залажал, то тестовая сцена полностью готова, просто в ней надо проверить работоспособность компоненты. Причём замечу, что одно вхождение hitbox в hurtbox должно фиксировать ровно 1 атаку.

Прикреплять в Pull-request тестовую сцену **не надо**, только скрипт hitbox'а с реализацией.

**Comment by WaterCatt** [comment]
Реализовал компоненту BasicHitBox в #24
