### ISSUE TITLE
Прототип передвижения персонажа

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#4]
**Общее описание**
Сделать прототип механик передвижения игрока.

**ТЗ**
Сделать новую сцену, у которой в корне будет узел `CharacterBody2D`. В качестве спрайта пока можно использовать заглушку в виде иконки Godot.
Реализовать следующие механики (системы) передвижения:
- [Передвижение](https://github.com/Dkoplik/Paint-it-Black/blob/main/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5)
- [Гравитация и падение](https://github.com/Dkoplik/Paint-it-Black/blob/main/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D0%B3%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%B0%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5)
- [Прыжок](https://github.com/Dkoplik/Paint-it-Black/blob/main/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D0%BF%D1%80%D1%8B%D0%B6%D0%BE%D0%BA)
- [Скольжение по стенам](https://github.com/Dkoplik/Paint-it-Black/blob/main/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE-%D1%81%D1%82%D0%B5%D0%BD%D0%B0%D0%BC)
- [Прыжок от стен](https://github.com/Dkoplik/Paint-it-Black/blob/main/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D0%BF%D1%80%D1%8B%D0%B6%D0%BE%D0%BA-%D0%BE%D1%82-%D1%81%D1%82%D0%B5%D0%BD)

Для систем передвижения стоит создать отдельный кастомный узел из обычного `Node`, в котором будут все необходимые функции для взаимодействия с передвижением персонажа. Иначе говоря, у узла со скриптом передвижения должен быть такой интерфейс, чтобы его можно было использовать как у игрока, так и у ИИ.

В корневом узле сцены игрока сделать скрипт с обработкой управления игрока, который задействует дочерний узел с механиками передвижения. Управление стандартное: A/D и пробел.

Если возникли вопросы по заданию, то писать сюда, в комментарии.

**Comment by Dkoplik** [comment]
Предпоследние 2 абзаца можно исключить, так как это прототип а не полноценная реализация. Когда появится нормальная архитектура, укажу в новом issue конкретный интерфейс узла. На данный же момент нет необходимости в строгом разделении по узлам, нужно просто протестировать механики и получить какие-то наработки.

**Comment by xzxolop** [comment]
Задание выполнил в коммитах: 0798687ac0dfdc7d1b670c22412dffd3fd339334 ed2dec744fdc77becfea837999975209fc799582 8f583c360f2c17c8e2eb337daa5233db1cf18ce2 0d81b3e3d11d06ef9479e1b82db30c2b3c4d6614 b16f28b9280de518a966ddfeb4f36384a188c331
