### ISSUE TITLE
Не работает прыжок от правых стен

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#47]
**Описание**
Если стена находится справа от игрока, то прыжок от стен не работает вовсе.

**Воспроизведение**
Шаги по воспроизведению ошибки:
1. Запустить тестовую сцену
2. Подойти к правой границе
3. Прыгнуть на стену и попытаться отпрыгнуть от неё
4. Обнаружить отсутствие прыжка от стены

**Ожидаемое поведение**
Прыжок от стены

**Скриншоты**
Отсутствуют

**Comment by xzxolop** [comment]
Интересное наблюдение: прыжок от стены работает, если зажать клавишу A/D

**Comment by Dkoplik** [comment]
> Интересное наблюдение: прыжок от стены работает, если зажать клавишу A/D

Оно так работало и раньше, при этом даже с этим замечанием прыжок от правой стены не работает:
![image](https://github.com/Dkoplik/Paint-it-Black/assets/101090199/46338cec-8848-45de-a336-75d92c7e3067)

Однако, по какой-то причине, прыжок от правой стены вот здесь иногда срабатывает:
![image](https://github.com/Dkoplik/Paint-it-Black/assets/101090199/894214c9-d224-4f05-8432-ff5c275b9385)

Поскольку как скольжение по стене, так и прыжок задействуют коллайдер от `CharacterBody2D` и используют метод `is_on_wall()`, то в них проблем нет, так как скольжение работает без проблем. Скорее всего, беда где-то в проверке условия на выполнение прыжка от стены.

**Comment by Dkoplik** [comment]
> Интересное наблюдение: прыжок от стены работает, если зажать клавишу A/D

Пока такое исправлять не нужно, сейчас не уверен, желательно ли такое поведение или нет. Но чтобы это исправить, можно будет игроку добавить ещё один коллайдер через `Area2D`, который при пересечении с коллайдерами от стен будет испускать сигнал. Соответственно, вместо метода `is_on_wall()` надо будет использовать этот сигнал, так что часть кода придётся переписать для такого решения. Также новый коллайдер должен быть на 1-3 пикселя выходить за границы коллайдера от `CharacterBody2D`, чтобы пересечение со стеной фиксировалось, но при этом `CharacterBody2D` не мог оттлокнуть от стены.

**Comment by Dkoplik** [comment]
Исправлено в PR #95
