### ISSUE TITLE
Тестовый спрайт игрока

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#6]
**Общее описание**
Сделать тестовый спрайт игрока.

**ТЗ**
По описанию из диздока нарисовать спрайт [игрока](https://github.com/Dkoplik/Paint-it-Black/blob/develop/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#%D0%B8%D0%B3%D1%80%D0%BE%D0%BA) с видом сбоку и направлением вправо. Спрайт попытаться нарисовать подробным, не задумываясь об необходимости его анимировать. Только когда данная тестовая версия игрока будет готова, посмотрим, как его можно будет упростить для последующей раскрадровки.

**Срок**
Крайний срок до воскресенья 29.10.2023, этот спрайт надо ещё успеть анимировать.

**Comment by Dkoplik** [comment]
Размер спрайта примерно 32x32, возможно, высоту надо будет сделать 34-36 пикселя. Если вдруг появиться необходимость сильно поменять размер спрайта, то писать сюда, обсудим, насколько это нужно будет.

**Comment by Dkoplik** [comment]
Размер спрайта был обновлён до 64x64.

**Comment by Gamzatov1** [comment]
сделал спрайт в комите 61da22e1c611dae61d5a6364b5940ba1cd99fd10
