### ISSUE TITLE
Нарисовать тайлы для построения уровней

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/Paint-it-Black#72]
**ТЗ**
Нарисовать базовый [TileSet](https://github.com/Dkoplik/Paint-it-Black/blob/develop/%D0%94%D0%98%D0%97%D0%94%D0%9E%D0%9A.md#tileset-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80-%D1%82%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2), все критерии в диздоке.

**Comment by Gamzatov1** [comment]
Закрыл issue в коммите 2990486f91b7bbc65599947b663d8742fae2f019

**Comment by Gamzatov1** [comment]
Обновил тайлы в коммите afc4af5b84440c05989cc0ec95ed1bffc3f12fc8

**Comment by Gamzatov1** [comment]
Обновил тайлы в коммите 9313e7e8b802f75b401017cacafbb6cc089e7fb1
